### ISSUE TITLE
Openspot problem

### ISSUE THREAD

**Issue by SA7BNT** [juribeparada/DMR2YSF#1]
Yesterday we tested DMR2YSF and discover that there may be a compatibility problem between DMR2YSF and Openspot. 
When the OM is talking via the Openspot and I receive it via DMR2YSF he has (dropouts) every sec. 
If he is using an MMDVM singleHut and is talking with C4FM all audio is fine. 
The problem was confirmed from another OM who was listing via DMR2YSF.
Is that a known issue?

Here is an short clip.
[https://youtu.be/0DCd-nX3Aik](url)
![dmr2ysf](https://user-images.githubusercontent.com/35367117/46583895-7811c580-ca5d-11e8-92db-2f0a9273b22a.jpg)

SA7BNT

**Comment by juribeparada** [comment]
Sorry but I don't have any Openspot, I can't help so much. I only can suggest to enable network debug and see if data packets from Openspot device are sent continuously or there are big time gaps. In MMDVM's YSF implementation there is not any network jitter/delay buffer for now.

**Comment by SA7BNT** [comment]
Sorry the late replay.
Here is a log from DMR2YSF
![bildschirmfoto 2018-10-08 um 19 30 44](https://user-images.githubusercontent.com/35367117/46624343-b4fabc80-cb30-11e8-99e4-7b94efc833f6.png)
Hope that will help
SA7BNT

**Comment by juribeparada** [comment]
Unfortunately that log doesn't have enough information. Some questions:
1) I imagine you connect to some YSF Reflector. What about other users connected to that reflector, but using a proper YSF radio?
2) Are you using latest source code of DMR2YSF?. Just in case, this repository is old. The latest source code is here: https://github.com/juribeparada/MMDVM_CM
3) I will need a full log with YSF network debug information. In DMR2YSF.ini, enable Debug=1 in [YSF Network] section (I've just added it, you will need to update from MMDVM_CM). I am interested in "YSF Network Data Received" hex dump.

**Comment by SA7BNT** [comment]
Can be closed. Update fixt my issue
